// AUTO-GENERATED by seo-scripts/generate-blog-manifest.js — do not edit by hand.
// Regenerated on every build (npm run build) from seo/content/*.md frontmatter.
// Used by src/components/BlogSection.tsx (SPA) and seo-scripts/prerender.js (SSG)
// so the "From the blog" home section stays in sync in both places.

export interface BlogManifestPost {
  slug: string;
  title: string;
  description: string;
  date: string;
  path: string;
}

export const blogManifest: Record<string, BlogManifestPost[]> = {
  "en": [
    {
      "slug": "heic-in-canva",
      "title": "How to Use HEIC Files in Canva (Convert to JPG First)",
      "description": "Canva says \"unsupported file type\" when you upload an iPhone HEIC photo? Here's why Canva rejects HEIC and the fastest free way to convert HEIC to JPG so it uploads instantly.",
      "date": "2026-07-17",
      "path": "/blog/heic-in-canva/"
    },
    {
      "slug": "upload-heic-to-wordpress",
      "title": "Why WordPress Won't Accept HEIC (and How to Upload Your Photos)",
      "description": "WordPress says \"this file type is not permitted for security reasons\" when you upload a HEIC photo? Here's why WordPress blocks HEIC and the simplest way to get your iPhone photos onto your site.",
      "date": "2026-07-14",
      "path": "/blog/upload-heic-to-wordpress/"
    },
    {
      "slug": "heic-codec-windows-10",
      "title": "HEIC Codec on Windows 10 — Why It Costs Money (and the Free Fix)",
      "description": "Windows 10 asks you to buy the HEVC Video Extensions codec to open HEIC photos? Here's why Microsoft charges for it, and how to open iPhone HEIC files free without paying for a codec.",
      "date": "2026-07-11",
      "path": "/blog/heic-codec-windows-10/"
    },
    {
      "slug": "heic-in-google-drive",
      "title": "HEIC in Google Drive and Docs — How to View and Use Them",
      "description": "Google Drive shows \"no preview available\" for HEIC photos and Google Docs won't insert them? Here's why, and how to convert HEIC to JPG so it previews and inserts anywhere.",
      "date": "2026-07-09",
      "path": "/blog/heic-in-google-drive/"
    },
    {
      "slug": "how-to-convert-heic-to-jpg-android",
      "title": "How to Convert HEIC to JPG on Android (Free, No App) 2026",
      "description": "Convert HEIC to JPG on Android right in your browser — no app, no upload. Fix Samsung Gallery and Google Photos HEIC issues, plus batch convert free.",
      "date": "2026-07-09",
      "path": "/blog/how-to-convert-heic-to-jpg-android/"
    },
    {
      "slug": "heic-vs-raw-iphone",
      "title": "HEIC vs RAW on iPhone: Which Should You Shoot? (2026)",
      "description": "HEIC vs RAW iPhone comparison: file size, quality, and editing latitude. Learn should i shoot raw or heic and how Apple ProRAW vs HEIC really differ.",
      "date": "2026-07-07",
      "path": "/blog/heic-vs-raw-iphone/"
    },
    {
      "slug": "open-heic-on-chromebook",
      "title": "How to Open HEIC Files on a Chromebook (Free, No Install)",
      "description": "Chromebook can't open HEIC photos from your iPhone? ChromeOS has no HEIC support and you can't install Windows apps. Here's the free browser-based way to view and convert HEIC on a Chromebook.",
      "date": "2026-07-07",
      "path": "/blog/open-heic-on-chromebook/"
    },
    {
      "slug": "attach-heic-to-email",
      "title": "Can't Attach HEIC to Email? Fix for Outlook and Gmail",
      "description": "HEIC photos won't open when you email them from your iPhone? Here's why HEIC attachments fail in Outlook and Gmail, and how to send iPhone photos everyone can open.",
      "date": "2026-07-05",
      "path": "/blog/attach-heic-to-email/"
    },
    {
      "slug": "copytrans-heic-alternatives",
      "title": "CopyTrans HEIC Alternatives: Free Ways to Open and Convert HEIC on Windows (2026)",
      "description": "CopyTrans HEIC is free for personal use only and requires installation. Compare the best alternatives — iMazing HEIC Converter, Microsoft's codecs, and free online converters that need no install.",
      "date": "2026-07-04",
      "path": "/blog/copytrans-heic-alternatives/"
    },
    {
      "slug": "heic-in-photoshop",
      "title": "How to Open HEIC Files in Photoshop (2026 Fix)",
      "description": "Photoshop won't open your HEIC files or shows \"could not complete your request because it is not the right kind of document\"? Here's why, and three ways to open iPhone HEIC photos in Photoshop for free.",
      "date": "2026-07-03",
      "path": "/blog/heic-in-photoshop/"
    },
    {
      "slug": "heic-to-mp4-live-photos",
      "title": "HEIC to MP4: How to Convert Live Photos to Video",
      "description": "Want to convert HEIC to MP4? What you actually have is a Live Photo. Here's how to save iPhone Live Photos as MP4 video on iPhone, Mac, and Windows — free.",
      "date": "2026-07-02",
      "path": "/blog/heic-to-mp4-live-photos/"
    },
    {
      "slug": "heic-vs-jpeg",
      "title": "HEIC vs JPEG: Which Format Is Better? Quality, Size & Compatibility Compared",
      "description": "HEIC vs JPEG compared — file size, image quality, compatibility, and when to use each. Plus what HEIF vs HEIC means and whether converting HEIC to JPG loses quality.",
      "date": "2026-06-29",
      "path": "/blog/heic-vs-jpeg/"
    },
    {
      "slug": "convert-heic-to-jpg-on-iphone",
      "title": "How to Convert HEIC to JPG on iPhone (5 Easy Ways, 2026)",
      "description": "Convert HEIC to JPG directly on your iPhone — with the Files app, by email, in Settings, or online. Plus how to stop your iPhone from taking HEIC photos entirely.",
      "date": "2026-06-25",
      "path": "/blog/convert-heic-to-jpg-on-iphone/"
    },
    {
      "slug": "how-to-open-heic-files",
      "title": "How to Open HEIC Files on Windows 11, Windows 10, and Mac (2026 Guide)",
      "description": "Learn how to open HEIC files on Windows 11, Windows 10, Mac, and online. Free HEIC viewer options, built-in tools, and how to convert HEIC to JPG when you need universal compatibility.",
      "date": "2026-06-22",
      "path": "/blog/how-to-open-heic-files/"
    }
  ],
  "de": [
    {
      "slug": "heic-vs-jpeg",
      "title": "HEIC vs JPEG: Unterschiede, Qualität und wann welches Format? (2026)",
      "description": "HEIC vs JPEG im Vergleich: Dateigröße, Bildqualität und Kompatibilität. Wir erklären den Unterschied zwischen HEIC und JPEG – und wann welches Format sinnvoll ist.",
      "date": "2026-07-16",
      "path": "/de/blog/heic-vs-jpeg/"
    },
    {
      "slug": "copytrans-heic-alternativen",
      "title": "CopyTrans HEIC Alternativen 2026: Die besten Optionen für Windows im Vergleich",
      "description": "CopyTrans HEIC ist nur privat kostenlos & braucht eine Installation. Wir vergleichen Alternativen wie iMazing und zeigen, wie Sie HEIC in JPG umwandeln – ganz ohne Installation.",
      "date": "2026-07-13",
      "path": "/de/blog/copytrans-heic-alternativen/"
    },
    {
      "slug": "heic-in-jpg-auf-iphone",
      "title": "HEIC in JPG umwandeln auf dem iPhone (5 einfache Wege, 2026)",
      "description": "HEIC in JPG umwandeln auf dem iPhone: 5 einfache Methoden ohne App-Installation, plus wie du das iPhone-Fotoformat dauerhaft auf JPG umstellst.",
      "date": "2026-07-10",
      "path": "/de/blog/heic-in-jpg-auf-iphone/"
    },
    {
      "slug": "heic-datei-oeffnen",
      "title": "HEIC-Datei öffnen — so geht's unter Windows 11, Windows 10 und am Mac (2026)",
      "description": "HEIC-Datei öffnen unter Windows 11, Windows 10, Mac oder direkt im Browser — kostenlos. Alle Methoden im Überblick, plus HEIC in JPG umwandeln, wenn das Format Probleme macht.",
      "date": "2026-06-26",
      "path": "/de/blog/heic-datei-oeffnen/"
    }
  ],
  "ja": [
    {
      "slug": "heic-vs-jpeg",
      "title": "HEICとJPEGの違いとは？画質・容量・互換性を徹底比較【2026年版】",
      "description": "HEICとJPEGの違いを容量・画質・互換性の観点で比較。HEICとは何か、HEIFとの違い、どっちを使うべきかを分かりやすく解説します。",
      "date": "2026-07-16",
      "path": "/ja/blog/heic-vs-jpeg/"
    },
    {
      "slug": "iphone-heic-jpeg-henkan",
      "title": "iPhoneでHEICをJPEGに変換する方法【2026年最新版】",
      "description": "iPhoneで撮った写真がHEIC形式で開けない・共有できない…そんな悩みを解決。iPhoneでHEICをJPEGに変換する方法と、設定を変更して最初からJPEGで撮影する方法を解説します。",
      "date": "2026-07-11",
      "path": "/ja/blog/iphone-heic-jpeg-henkan/"
    },
    {
      "slug": "heic-hirakenai",
      "title": "HEICが開けない？Windows 11・Windows 10・Macでの開き方と対処法【2026年版】",
      "description": "HEICファイルが開けないときの対処法を全部まとめました。Windows 11・Windows 10・Macでの開き方、ブラウザで表示する方法、HEICをJPEGに変換する方法まで — すべて無料。",
      "date": "2026-07-03",
      "path": "/ja/blog/heic-hirakenai/"
    }
  ],
  "es": [
    {
      "slug": "pasar-heic-a-jpg-en-iphone",
      "title": "Cómo pasar de HEIC a JPG en iPhone (5 métodos fáciles, 2026)",
      "description": "Pasa tus fotos de HEIC a JPG directamente en el iPhone — con la app Archivos, por correo, desde Ajustes o online. Y cómo hacer que el iPhone deje de hacer fotos en HEIC.",
      "date": "2026-07-05",
      "path": "/es/blog/pasar-heic-a-jpg-en-iphone/"
    },
    {
      "slug": "abrir-archivos-heic",
      "title": "Cómo abrir archivos HEIC en Windows 11, Windows 10 y Mac (2026)",
      "description": "Aprende a abrir archivos HEIC en Windows 11, Windows 10, Mac o directamente en el navegador — gratis. Todos los métodos, y cómo pasar de HEIC a JPG si el formato te da problemas.",
      "date": "2026-06-30",
      "path": "/es/blog/abrir-archivos-heic/"
    }
  ],
  "fr": [
    {
      "slug": "convertir-heic-en-jpg-sur-iphone",
      "title": "Convertir HEIC en JPG sur iPhone — 5 méthodes faciles (2026)",
      "description": "Convertissez vos photos HEIC en JPG directement sur iPhone — avec l'app Fichiers, par e-mail, dans les Réglages ou en ligne. Et comment empêcher l'iPhone de prendre des photos en HEIC.",
      "date": "2026-07-08",
      "path": "/fr/blog/convertir-heic-en-jpg-sur-iphone/"
    },
    {
      "slug": "ouvrir-fichier-heic",
      "title": "Ouvrir un fichier HEIC sur Windows 11, Windows 10 et Mac — guide 2026",
      "description": "Comment ouvrir un fichier HEIC gratuitement sur Windows 11, Windows 10, Mac ou directement dans le navigateur. Pourquoi vos photos iPhone sont en HEIC, et comment les convertir en JPG.",
      "date": "2026-06-27",
      "path": "/fr/blog/ouvrir-fichier-heic/"
    }
  ],
  "pt": [
    {
      "slug": "converter-heic-para-mp4",
      "title": "Converter HEIC para MP4: o Segredo do Live Photo (2026)",
      "description": "Quer converter HEIC para MP4? Na maioria das vezes é um Live Photo. Veja como transformar HEIC em MP4 e salvar Live Photos como vídeo no iPhone, Mac e Windows.",
      "date": "2026-07-12",
      "path": "/pt/blog/converter-heic-para-mp4/"
    },
    {
      "slug": "converter-heic-para-jpg-no-iphone",
      "title": "Como converter HEIC para JPG no iPhone (5 jeitos fáceis, 2026)",
      "description": "Converta HEIC para JPG direto no iPhone — com o app Arquivos, por e-mail, nos Ajustes ou online. E como fazer o iPhone parar de tirar fotos em HEIC.",
      "date": "2026-07-06",
      "path": "/pt/blog/converter-heic-para-jpg-no-iphone/"
    },
    {
      "slug": "abrir-arquivo-heic",
      "title": "Como abrir arquivo HEIC no Windows 11, Windows 10 e Mac (2026)",
      "description": "Aprenda como abrir arquivo HEIC no Windows 11, Windows 10, Mac ou direto no navegador — grátis. Todos os métodos, e como converter HEIC para JPG quando o formato der problema.",
      "date": "2026-07-01",
      "path": "/pt/blog/abrir-arquivo-heic/"
    }
  ],
  "ko": [
    {
      "slug": "heic-yeolgi",
      "title": "HEIC 열기 완벽 가이드 — HEIC 뷰어로 쉽게 보는 방법 (2026)",
      "description": "HEIC 파일 열기가 안 될 때 해결법. 윈도우, 맥, 안드로이드에서 heic 보기부터 온라인 heic 뷰어, heic jpg 변환까지 한 번에 정리했습니다.",
      "date": "2026-07-15",
      "path": "/ko/blog/heic-yeolgi/"
    }
  ],
  "nl": [
    {
      "slug": "heic-bestand-openen",
      "title": "HEIC-bestand openen: complete handleiding voor Windows, Mac en Android (2026)",
      "description": "HEIC-bestand openen op Windows, Mac of Android? Ontdek wat een HEIC-bestand is en hoe je het eenvoudig kunt bekijken of omzetten naar JPG.",
      "date": "2026-07-14",
      "path": "/nl/blog/heic-bestand-openen/"
    }
  ],
  "sv": [],
  "no": [],
  "da": []
};
